# @Author: guiguan
# @Date:   2017-01-30T10:14:58+11:00
# @Last modified by:   guiguan
# @Last modified time: 2017-06-21T09:23:04+10:00



pipeline:
  cienvy_core_mongodb-3.4:
    image: southbanksoftware/cienvy:node-nm-mongo
    pull: true
    commands:
      - yarn install
      - yarn test
  cienvy_core_mongodb-3.2:
    image: southbanksoftware/cienvy:node-nm-mongo-3.2
    pull: true
    commands:
      - yarn install
      - yarn test
    when:
      status: [success, failure]
  cienvy_core_mongodb-3.0:
    image: southbanksoftware/cienvy:node-nm-mongo-3.0
    pull: true
    commands:
      - yarn install
      - yarn test
    when:
      status: [success, failure]
branches: master
