# @Author: Guan Gui <guiguan>
# @Date:   2016-06-02T14:58:00+10:00
# @Email:  root@guiguan.net
# @Last modified by:   guiguan
# @Last modified time: 2018-03-05T16:03:11+11:00

extends: [airbnb, plugin:flowtype/recommended]
parser: babel-eslint
env:
  browser: true
  node: true
  mocha: true
  es6: true
rules:
  arrow-body-style: off
  key-spacing: off
  object-property-newline: off
  no-cond-assign: [error, except-parens]
  no-nested-ternary: off
  no-shadow: off
  no-eval: off
  eqeqeq: off
  array-callback-return: off
  no-param-reassign: off
  space-before-function-paren: off
  global-require: off
  consistent-return: off
  quote-props: off
  no-underscore-dangle: off
  prefer-const: [error, {ignoreReadBeforeAssign: true}]
  max-len: off
  prefer-template: off
  object-curly-spacing: off
  comma-dangle: off
  indent: off
  no-console: off
  no-continue: off
  no-alert: off
  no-multiple-empty-lines: [2, {max: 3}]
  func-names: off
  new-cap: [2, {capIsNew: false}]
  import/default: off
  import/no-duplicates: off
  import/named: off
  import/namespace: off
  import/no-named-as-default: error
  # this requires eslint-import-resolver-node@0.3.0 to be installed in order for import/resolver settings to work
  import/no-unresolved: [error, {ignore: ["^[~]"]}]
  import/prefer-default-export: off
  import/no-extraneous-dependencies: off
  import/extensions: off
  react/prefer-stateless-function: off
  react/jsx-space-before-closing: off
  react/jsx-first-prop-new-line: off
  react/jsx-closing-bracket-location: off
  react/no-multi-comp: off
  react/no-did-mount-set-state: off
  no-unused-vars: [error, {argsIgnorePattern: ^_}]
  no-restricted-syntax: off
  no-unused-expressions: off
  newline-per-chained-call: off
  no-use-before-define: [error, {functions: false, classes: true}]
  linebreak-style: off
  function-paren-newline: off
  prefer-destructuring: [warn, {
    VariableDeclarator: {
      array: true,
      object: true
    },
    AssignmentExpression: {
      array: false,
      object: false
    }
  }, {
    enforceForRenamedProperties: false
  }]
  prefer-promise-reject-errors: warn
  object-curly-newline: [off, {
    ObjectExpression: { minProperties: 0, multiline: true },
    ObjectPattern: { minProperties: 0, multiline: true }
  }]
  flowtype/no-types-missing-file-annotation: off
  no-mixed-operators: off
  flowtype/generic-spacing: off
  arrow-parens: off
plugins: [react, import, flowtype]
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - src
globals:
  l: false
  log: false
  IS_PRODUCTION: false
